/**
 * load-tests/scenarios/compose-send.js
 *
 * Compose & Send load-test scenario.
 *
 * CLAUDE.md budgets:
 *   Email send time-to-delivered  < 2 000 ms  (enqueue portion only)
 *   API response (cloud) p99      < 200 ms
 *
 * NOTE: These tests hit the real send pipeline.  Use a dedicated
 * test domain (e.g. loadtest.alecrae.com) configured to accept
 * but not actually deliver externally, or pass SKIP_REAL_SEND=1
 * to target the /v1/compose-assist endpoint (AI draft only, no send).
 *
 * Endpoints exercised:
 *   POST /v1/messages/send        — full send pipeline (enqueue to MTA)
 *   POST /v1/compose-assist/draft — AI-assisted draft (no send)
 *   GET  /v1/messages/:id         — poll message status after send
 *
 * Rate limit: 100 req/min per API key for /send.
 *
 * Usage:
 *   k6 run \
 *     -e BASE_URL=https://api.alecrae.com \
 *     -e AUTH_TOKEN=<bearer_token> \
 *     -e FROM_EMAIL=loadtest@alecrae.com \
 *     -e TO_EMAIL=sink@alecrae.com \
 *     [-e SKIP_REAL_SEND=1] \
 *     load-tests/scenarios/compose-send.js
 */

import { sleep } from "k6";
import http from "k6/http";
import { check } from "k6";
import { Counter, Trend } from "k6/metrics";
import { baseUrl, authToken, authHeaders, parseJson, randomId } from "../lib/helpers.js";
import { sendThresholds } from "../lib/thresholds.js";

// ─── Custom metrics ───────────────────────────────────────────────────────────

const sendErrors = new Counter("send_errors");
const enqueueLatency = new Trend("send_enqueue_ms");

// ─── Fixture helpers ──────────────────────────────────────────────────────────

const SUBJECT_TEMPLATES = [
  "Load test email {id} — please ignore",
  "Automated test message {id}",
  "AlecRae performance test {id}",
  "Internal test {id} — do not reply",
];

function makeSubject() {
  const id = randomId();
  const tpl = SUBJECT_TEMPLATES[Math.floor(Math.random() * SUBJECT_TEMPLATES.length)];
  return tpl.replace("{id}", id);
}

function makeSendBody(fromEmail, toEmail) {
  return {
    from: {
      email: fromEmail,
      name: "AlecRae Load Test",
    },
    to: [{ email: toEmail }],
    subject: makeSubject(),
    text: "This is an automated load-test message generated by k6. Please disregard.",
    html: "<p>This is an automated load-test message generated by k6. Please disregard.</p>",
    tags: [{ name: "source", value: "load-test" }],
  };
}

// ─── Scenario config ──────────────────────────────────────────────────────────

export const options = {
  scenarios: {
    /**
     * send_email: enqueue path — measures time from POST to 200 acknowledgement.
     * Kept at low VUs because send rate-limit is 100 req/min per key and
     * we don't want to flood an actual MTA queue.
     */
    send_email: {
      executor: "ramping-vus",
      startVUs: 0,
      stages: [
        { duration: "30s", target: 3  },
        { duration: "2m",  target: 8  },
        { duration: "1m",  target: 5  },
        { duration: "30s", target: 0  },
      ],
      gracefulRampDown: "15s",
      tags: { scenario: "send_email" },
      exec: "sendEmail",
    },
    /**
     * compose_assist: AI draft generation (no MTA involvement).
     * Higher concurrency is safe — no rate limit on compose-assist.
     */
    compose_assist: {
      executor: "ramping-vus",
      startVUs: 0,
      stages: [
        { duration: "30s", target: 10 },
        { duration: "2m",  target: 20 },
        { duration: "30s", target: 0  },
      ],
      gracefulRampDown: "15s",
      tags: { scenario: "compose_assist" },
      exec: "composeAssist",
      startTime: "20s",
    },
  },
  thresholds: sendThresholds,
};

// ─── Scenario functions ───────────────────────────────────────────────────────

export function sendEmail() {
  // Allow test runners to skip real sends (e.g. against staging with no real MTA)
  if (__ENV.SKIP_REAL_SEND === "1") {
    sleep(1);
    return;
  }

  const token = authToken();
  const fromEmail = __ENV.FROM_EMAIL || "loadtest@alecrae.com";
  const toEmail   = __ENV.TO_EMAIL   || "sink@alecrae.com";
  const url = `${baseUrl()}/v1/messages/send`;

  const start = Date.now();
  const res = http.post(
    url,
    JSON.stringify(makeSendBody(fromEmail, toEmail)),
    {
      headers: authHeaders(token),
      tags: { name: "send_email" },
    }
  );
  enqueueLatency.add(Date.now() - start);

  const ok = check(res, {
    "send status 200 or 201": (r) => r.status === 200 || r.status === 201,
    "send returns message id": (r) => {
      const body = parseJson(r);
      return body?.data?.id !== undefined || body?.data?.messageId !== undefined;
    },
  });

  if (!ok) sendErrors.add(1);

  // Throttle: 100 req/min limit → minimum ~0.6 s per VU per iteration.
  // Use a larger sleep to be polite to staging/prod.
  sleep(Math.random() * 4 + 3);
}

export function composeAssist() {
  const token = authToken();
  const url = `${baseUrl()}/v1/compose-assist/draft`;

  const prompts = [
    "Reply to a client asking for a project status update",
    "Write a follow-up email to a job candidate after an interview",
    "Decline a meeting politely but firmly",
    "Ask a colleague to review a document by end of day",
    "Thank a vendor for their prompt delivery",
  ];

  const prompt = prompts[Math.floor(Math.random() * prompts.length)];

  const body = {
    prompt,
    tone: "professional",
    length: "short",
  };

  const res = http.post(url, JSON.stringify(body), {
    headers: authHeaders(token),
    tags: { name: "compose_assist" },
  });

  check(res, {
    "compose_assist not 5xx": (r) => r.status < 500,
    "compose_assist has body": (r) => r.body && r.body.length > 0,
  });

  sleep(Math.random() * 3 + 2);
}
