apiVersion: v1
kind: Service
metadata:
  name: inbound
  namespace: emailed
  labels:
    app.kubernetes.io/name: inbound
    app.kubernetes.io/component: mail
    app.kubernetes.io/part-of: emailed-platform
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: nlb
    service.beta.kubernetes.io/aws-load-balancer-scheme: internet-facing
    service.beta.kubernetes.io/aws-load-balancer-cross-zone-load-balancing-enabled: "true"
spec:
  type: LoadBalancer
  externalTrafficPolicy: Local
  ports:
    - name: smtp
      port: 25
      targetPort: smtp
      protocol: TCP
    - name: http
      port: 8025
      targetPort: http
      protocol: TCP
  selector:
    app.kubernetes.io/name: inbound
