apiVersion: v1
kind: Service
metadata:
  name: jmap
  namespace: emailed
  labels:
    app.kubernetes.io/name: jmap
    app.kubernetes.io/component: mail
    app.kubernetes.io/part-of: emailed-platform
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: nlb
    service.beta.kubernetes.io/aws-load-balancer-scheme: internet-facing
    service.beta.kubernetes.io/aws-load-balancer-cross-zone-load-balancing-enabled: "true"
spec:
  type: LoadBalancer
  externalTrafficPolicy: Local
  ports:
    - name: http
      port: 8080
      targetPort: http
      protocol: TCP
    - name: imaps
      port: 993
      targetPort: imaps
      protocol: TCP
  selector:
    app.kubernetes.io/name: jmap
