apiVersion: v1
kind: Service
metadata:
  name: reputation
  namespace: emailed
  labels:
    app.kubernetes.io/name: reputation
    app.kubernetes.io/component: backend
    app.kubernetes.io/part-of: emailed-platform
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 80
      targetPort: http
      protocol: TCP
  selector:
    app.kubernetes.io/name: reputation
